const exerciseCode = {
    "Seated Incline Cable Press": "seatedinclinecablepress",
    "TRX Suspended Knee Tucks": "trxsuspendedkneetucks",
    "Walking Abduction": "walkingabduction",
    "Arm circle": "armcircles",
    "Battle Ropes-Alternate Waves": "battleropesalternatewaves",
    "Side Crunches": "sidecrunches",
    "Pigeon Stretch": "pigeonstretch",
    "Dumbbell Halo": "dumbbellhalo",
    "Front Squat": "frontsquat",
    "Dumbbell Squat": "frontsquat",
    "Side Plank With Staight Leg": "sideplankwithstaightleg",
    "Side Lunge": "sidelunge",
    "Bench Dips": "benchdips",
    "Dumbbell Jack Press": "dumbbelljackpress",
    "Box Jumps": "boxjumps",
    "Barbell Drag Curl": "barbelldragcurl",
    "Partner Standing Row Withresistance Tubing": "partnerstandingrowwithresistancetubing",
    "Seated Row": "seatedrow",
    "Supine Dead Bug": "supinedeadbug",
    "Punching Bag Cardio": "punchingbagcardio",
    "Dirty Dog": "dirtydog",
    "Side Plank Row": "sideplankrow",
    "Double Unders": "doubleunders",
    "Standing Dumbbell Rotation": "standingdumbbellrotation",
    "Diamond push ups": "diamondpushups",
    "Decline Push up": "declinepushup",
    "Claping push ups": "clapingpushups",
    "Spider-man Plank": "spidermanplank",
    "Supine Shoulder Flexion": "supineshoulderflexion",
    "Child Pose to Push-up": "childposetopushup",
    "Plank Jump-ins": "plankjumpins",
    "Seated Overhead Press": "seatedoverheadpress",
    "Dumbbell Shoulder Press": "dumbbellshoulderpress",
    "Jump Squat": "jumpsquat",
    "Clamshell": "clamshell",
    "Handstand against wall": "handstandagainstwall",
    "Supine Hamstrings Stretch": "supinehamstringsstretch",
    "Tuck Jump": "tuckjump",
    "Push-Ups With Single-Leg Raise": "pushupswithsinglelegraise",
    "Plank leg raise": "planklegraise",
    "Medicine Ball Overhead Slams": "medicineballoverheadslams",
    "Lateral Crawls": "lateralcrawls",
    "Plank-Ups": "plantkups",
    "Spider Walks": "spiderwalks",
    "Push-Up With Staggered Hands": "pushupwithstaggeredhands",
    "Single Arm Plank": "singlearmplank",
    "Bear Crawl Exercise": "bearcrawlexercise",
    "TRX Suspended Push-ups": "trxsuspendedpushups",
    "Plank Up Down": "plankupdown",
    "Mountain Climbers": "mountainclimbers",
    "Single Leg Stand": "singlelegstand",
    "Squat Jump": "squatjump",
    "Banded External Rotations": "bandedexternalrotations",
    "Banded Pull Through": "bandedpullthrough",
    "Squat To Row": "squattorow",
    "Supine Sinal Twist With Rib Grab And Progressions": "supinesinaltwistwithribgrabandprogressions",
    "T-Spine Rotations": "tspinerotations",
    "Wrist Curl Flexion": "wristcurlflexion",
    "Wrist Curl Extension": "wristcurlextension",
    "Hang Clean": "hangclean",
    "Standing Hay Baler": "standinghaybaler",
    "Standing Wood Chop": "standingwoodchop",
    "Hip Hinge": "hiphinge",
    "Burpee with Push up": "burpeewithpushup",
    "Standing Calf Raises-Wall": "standingcalfraiseswall",
    "High Knees": "highknees",
    "Warrior I": "warrior1",
    "Standing Chest Stretch": "standingcheststretch",
    "Standing Cable Front Raises": "standingcablefrontraises",
    "Lateral Lunge Wood Chop": "laterallungewoodchop",
    "Low Windmill": "lowwindmill",
    "Lateral Lunge": "laterallunge",
    "Lateral lunges": "laterallunges",
    "Lunge": "lunge",
    "Straight Arm Pressdown": "straightarmpressdown",
    "Single-Arm Chest Press": "singlearmchestpress",
    "Single-Arm Standing Split-Stance Band Press": "singlearmchestpress",
    "Diagonal Raise": "diagonalraise",
    "V-Raise": "vraise",
    "Triceps Pressdown": "tricepspressdown",
    "High Row": "highrow",
    "Standing Anti-Rotation Press": "standingantirotationpress",
    "Bottom-Up Press": "bottomuppress",
    "Rotational Uppercut": "rotationaluppercut",
    "Single Arm Overhead Press": "singlearmoverheadpress",
    "Waiter'S Carry": "waiterscarry",
    "Goblet Squat": "gobletsquat",
    "Squat": "squat",
    "Single-Arm Lateral Raise": "singlearmlateralraise",
    "Front Raise": "frontraise",
    "Squat Hold": "squathold",
    "Swing": "swing",
    "Sumo Deadlift": "sumodeadlift",
    "Overhead Triceps": "overheadtriceps",
    "Dumbell Military Press": "dumbellmilitarypress",
    "Kettlebell Deadlift": "kettlebelldeadlift",
    "Single Leg Squat": "singlelegsquat",
    "Dumbbell Forward Lunge": "dumbbellforwardlunge",
    "Banded Goodmorning": "bandedgoodmorning",
    "Cable Cross-Over": "cablecrossover",
    "PVC Pass Through": "pvcpassthrough",
    "Stationary Double Arm Swings": "stationarydoublearmswings",
    "Resistance Band Front Raise": "resistancebandfrontraise",
    "Kettlebell Sumo Squat": "kettlebellsumosquat",
    "Standing Row": "standingrow",
    "Hammer Curl": "hammercurl",
    "Anti-Rotation Reverse Lunge": "antiroationreverselunge",
    "Hip Circles": "hipcircles",
    "Barbell Good Mornings": "barbellgoodmornings",
    "Single-Arm,Single-Leg Romanian Dead Lift": "singlearmsinglelegromaniandeadlift",
    "Single Leg Push-Off": "singlelegpushoff",
    "Resistance Band Upright Row": "resistancebanduprightrow",
    "Face Pulls": "facepulls",
    "Inchworms": "inchworms",
    "Standing Shurg": "standingshurg",
    "Lateral Raise": "lateralraise",
    "Bulgarian Split Squat": "bulgariansplitsquat",
    "Overhead Mecine Ball Throws": "overheadmecineballthrows",
    "Clean And Press": "cleanandpress",
    "Sand Bag Clean": "sandbagclean",
    "Lateral Neck Flexion": "lateralneckflexion",
    "Seated Crunch": "seatedcrunch",
    "Seated Bent-Knee Biceps Stretch": "seatedbentkneebicepsstretch",
    "Modified Hurdler'S Stretch": "modifiedhurdlersstretch",
    "Seated Shoulder Press": "seatedshoulderpress",
    "Crab Toe Touches": "crabtoetouches",
    "Seated Butterfly Stretch": "seatedbutterflystretch",
    "Seated Medicine Ball Trunk Rotations": "seatedmedicineballtrunkrotations",
    "Russian Twist": "russiantwist",
    "Concentration Curl": "concentrationcurl",
    "Incline Chest Press": "inclinechestpress",
    "Incline Dumbbell Biceps curl": "inclinedumbbellbicepscurl",
    "Seated Arnold Press": "seatedamoldpress",
    "Seated Leg Extension": "seatedlegextension",
    "Seated High Back Row": "seatedhighbackrow",
    "Seated Lat Pulldown": "seatedlatpulldown",
    "Seated Hamstring Curl": "seatedhamstringcurl",
    "Lateral Shoulder Raise": "lateralshoulderraise",
    "Bodyweight Squat": "bodyweightsquat",
    "Power Clean": "powerclean",
    "Incline Reverse Fly": "inclinereversefly",
    "Dumbbell Partial Lateral Raise": "dumbbellpartiallateralraise",
    "Push Jerk - Barbell": "pushjerkbarbell",
    "Side Plank": "sideplank",
    "Pull down - Wide grip": "pulldownwidegrip",
    "Hip Rotations(Push-Up Postion)": "hiprotationspushuppostion",
    "Side Plank(Modified)": "sideplankmodified",
    "Pull-Ups": "pullups",
    "Medicine Ball Push-Ups": "medicineballpushups",
    "Burpee Box Job": "burpeeboxjob",
    "Standing Dorsi-Flexion(Calf Stretch)": "standingdorsiflexioncalfstretch",
    "Standing Chest Fly": "standingchestfly",
    "Pendalay Row": "pendalayrow",
    "TRX Hamstrings Curl": "trxhamstringscurl",
    "TRX Atomic Push-ups": "trxatomicpushups",
    "Standing Bicep Curl": "standingbicepcurl",
    "Standing Single-Leg Cable Rotation": "standingsinglelegcablerotation",
    "Single Arm Row": "singlearmrow",
    "Scapular Pull Ups": "scapularpullups",
    "Standing Hamstrings Curl": "standinghamstringscurl",
    "Rotator Cuff Internal Rotation": "rotatorcuffinternalrotation",
    "Rotator Cuff External Rotation": "rotatorcuffexternalrotation",
    "Bosu Trainer Mountain Climbers": "bosutrainermountainclimbers",
    "Hip Bridge": "hipbridge",
    "Supine Bicycle Crunches": "supinebicyclecrunches",
    "Lunge With Elbow Instep": "lungewithelbowinstep",
    "Cobra Exercise": "cobraexercise",
    "Contralateral Limb Raises": "contralaterallimbraises",
    "Side Lying Abduction": "sidelyingabduction",
    "Leg Raise": "legraise",
    "V-Ups": "vups",
    "Bent knee single leg Jackknife": "bentkneesinglelegjackknife",
    "Crunch": "crunch",
    "Glute Bridge Exercise": "glutebridgeexercise",
    "Single Leg V Ups": "singlelegvups",
    "Thomas Stretch": "thomasstretch",
    "Side lying quad stretch": "sidelyingquadstretch",
    "Side Lying Quadriceps Stretch": "sidelyingquadricepsstretch",
    "Leg Crossover Stretch": "legcrossoverstretch",
    "Reverse Ab Crunch": "reverseabcrunch",
    "Lying Chest Fly": "lyingchestfly",
    "Elevated Glute Bridge": "elevatedglutebridge",
    "Decline Dumbbell press": "declinedumbbellpress",
    "Happy baby pose": "happybabypose",
    "Pull-Over Crunch": "pullovercrunch",
    "Glute Bridge Single Leg Progression": "glutebridgesinglelegprogression",
    "Supermans": "supermans",
    "Chest Press": "chestpress",
    "Lying Pullovers": "lyingpullovers",
    "Close-Grip Bench Press": "closegripbenchpress",
    "Lying Hamstrings Curl": "lyinghamstringscurl",
    "Front Plank": "frontplank",
    "Spinal Twist With A Push-Pull Movement": "spinaltwistwithapushpullmovement",
    "Offset Single-Arm Chest Press": "offsetsinglearmchestpress",
    "Lying Barbell Triceps Extensions": "lyingbarbelltricepsextensions",
    "Hamstring curl w Ball": "hamstringcurlwball",
    "Camel Pose": "camelpose",
    "Kneeling Hip-Flexor Stretch": "kneelinghipflexorstretch",
    "Childs Pose": "childspose",
    "Kneeling Reverse Fly": "kneelingreversefly",
    "Roll Out": "rollout",
    "Single-Arm Medicine Ball Push-Ups": "singlearmmedicineballpushups",
    "Dumbbell Box Step ups": "dumbbellboxstepups",
    "Jump And Reach": "jumpandreach",
    "Seated High Back Rows": "seatedhighbackrows",
    "Jumping Jacks": "jumpingjacks",
    "Halo": "halo",
    "Power Push Down": "powerpushdown",
    "Seated Straddle Stretch": "seatedstraddlestretch",
    "TRX Hip Press": "trxhippress",
    "Walking Lunges With Twists": "walkinglungeswithtwists",
    "Roamanian Deadlift": "roamaniandeadlift",
    "Single Arm Swing": "singlearmswing",
    "High Windmill": "highwindmill",
    "Bicep Curl": "bicepcurl",
    "Reverse Bicep Curl": "reversebicepcurl",
    "Rotational Overhead Press": "rotationaloverheadpress",
    "Suitcase Carry": "suitcasecarry",
    "Single Arm High Pull": "singlearmhighpull",
    "Single Arm Overhead Squat": "singlearmoverheadsquat",
    "Reverse Lunge With Rotation": "reverselungewithrotation",
    "High Plank T-Spine Rotation": "highplanktspinerotation",
    "Renegade Row": "renegaderow",
    "Bent Knee Push-Up": "bentkneepushup",
    "Bosu Frog Jumps": "bosufrogjumps",
    "Farmer'S Carry": "farmerscarry",
    "Shrug": "shrug",
    "Hanging leg raises": "hanginglegraises",
    "Triceps Pushdowns": "tricepspushdowns",
    "Squat To Overhead Press": "squattooverheadpress",
    "Bent Row": "bentrow",
    "Assisted Pull-Up": "assistedpullup",
    "Pull Down- Close grip": "pulldownclosegrip",
    "Chin-Ups": "chinups",
    "Parallel Bar Dips": "parallelbardips",
    "TRX Chest Press": "trxchestpress",
    "Resistance Band Lateral Raise": "resistancebandlateralraise",
    "Tricep Kickbacks": "tricepkickbacks",
    "Dumbbell Jump Squat": "dumbbelljumpsquat",
    "Standing Lunge Stretch": "standinglungestretch",
    "Bird-Dog": "birddog",
    "Downward Facing Dog": "downwardfacingdog",
    "Prone (Lying) Hamstrings Curl": "pronelyinghamstringscurl",
    "Bosu Mountain Climber with Push ups": "bosumountainclimberwithpushups",
    "Flutter Kicks": "flutterkicks",
    "Dumbbell Glute Bridge": "dumbbellglutebridge",
    "Shoulder Hug Stretch": "shoulderhugstretch",
    "Transverse Lunge": "transverselunge",
    "Standing Decline Cable Flyes": "standingdeclinecableflyes",
    "TRX Suspended Lunge": "trxsuspendedlunge",
    "Reverse Fly": "reversefly",
    "Seated Decline Cable Press": "seateddeclinecablepress",
    "Standing Incline Cable Flyes": "standinginclinecableflyes",
    "Seated Chest Press": "seatedchestpress",
    "Dumbbell Plank row": "dumbbellplankrow",
    "Barbell Upright Row": "barbelluprightrow",
    "Burpee": "burpee",
    "Rotational Slam": "rotationalslam",
    "Triceps Extension": "tricepsextension",
    "Reverse Burpees": "reverseburpees",
    "Single leg Jackknife with Medicine Ball": "singlelegjackknifewithmedicineball",
    "Push-Ups": "pushups",
    "Cycled Split-Squat Jump": "cycledsplitsquatjump",
    "Cobra to Child Pose": "cobratochildpose",
    "Snatch": "snatch",
    "Machine Cable Kickbacks": "machinecablekickbacks",
    "Kneeling Lat Pulldown": "kneelinglatpulldown",
    "Dumbbell Forward Lunge with Curl Arm Press": "dumbbellforwardlungewithcurlarmpress",
    "Single-Arm Band Row": "singlearmbandrow",
    "Standing Crunch": "standingcrunch",
    "Calf Raise": "calfraise",
    "Standing Rotational Chop": "standingrotationalchop",
    "Dead Lift": "deadlift",
    "Military Barbell Press": "militarybarbellpress",
    "TRX Overhead Triceps Extension": "trxoverheadtricepsextension",
    "Quadruped Bent-Knee Hip Extension": "quadrupedbentkneehipextension",
    "Cat-Cow": "catcow",
    "Standing Trunk Rotation": "standingtrunkrotation",
    "Dumbbell Forward Lunge with Bicep Curl": "dumbbellforwardlungewithbicepcurl",
    "Half Turkish Get-Up": "halfturkishgetup",
    "Seated Calf Stretch": "seatedcalfstretch",
    "Forward Lunge": "forwardlunge",
    "Double Push-Press": "doublepushpress",
    "Calf Raises": "calfraises",
    "Standing Gate Openers Frankensteins": "standinggateopenersfrankensteins",
    "Pause Squat Press Out": "pausesquatpressout",
    "Figure Eight": "figureeight",
    "Back Squat": "backsquat",
    "Supine Pelvic Tilts": "supinepelvictilts",
    "Reverse Lunge": "reverselunge",
    "Vertical Toe Touches": "verticaltoetouches",
    "Seated Leg Press Exercise": "seatedlegpressExercise",
    "Single-Arm Rotational Press": "singlearmrotationalpress",
    "Upward Facing Dog": "upwardfacingdog",
    "Push Press": "pushpress",
    "Standing Quad Stretch": "standingquadstretch",
    "Reverse Barbell Curl": "reversebarbellcurl",
    "World's greatest stretch": "worldsgreateststretch",
    "Single-Leg Romanian Deadlift": "singlelegromaniandeadlift",
    "Standing Hip Adduction": "standinghipadduction",
    "Kneeling Wood Chop": "kneelingwoodchop",
    "Front Squat To  Overhead Press": "frontsquattooverheadpress",
    "TRX Biceps Curl": "trxbicepscurl",
    "Seated Straddle With Side Reaches": "seatedstraddlewithsidereaches",
    "Wide grip Push Up": "widegrippushup",
    "TRX Single-arm Row": "trxsinglearmrow",
    "Kneeling Hay Baler": "kneelinghaybaler",
    "TRX Back Row": "trxbackrow",
    "TRX Suspended Pike": "trxsuspendedpike",
    "Close grip Push Up": "closegrippushup",
    "Step-Up": "stepup",
    "TRX Assisted Cross-Over Lunge With Arm Raise": "trxassistedcrossoverlungewitharmraise",
    "TRX Single-Arm Chest Press": "trxsinglearmchestpress",
    "Lunge With Overhead Press": "lungewithoverheadpress",
    "Standing Leg Extension": "standinglegextension",
    "Wrist Supination & Pronation Exercises": "wristsupinationpronationexercises",
    "Seated Close-Grip Chest Press": "seatedclosegripchestpress",
    "Seated Machine Close-Grip Shoulder Press": "seatedmachineclosegripshoulderpress",
    "TRX Assisted SIde Lunge With Arm Raise": "trxassistedsidelungewitharmraise",
    "Alternate Leg Push-Off": "alternatelegpushoff",
    "Seated Hip Openers": "seatedhipopeners",
    "Seared Cable Press": "searedcablepress",
    "Beast hold toe touches": "beastholdtoetouches",
    "Push Jerk - Kettlebells": "pushjerkkettlebells",
    "Turkish Get-Up": "turkishgetup",
    "Single Arm,Single Leg Plank": "singlearmsinglelegplank",
    "Seated Toe Touches": "seatedtoetouches",
    "Neck Flexion And Extension": "neckflexionandextension",
    "Downward Dog to Lunge": "downwarddogtolunge",
    "Knee Hugs to Lunge": "kneehugstolunge",
    "Cuban Press With PVC": "cubanpresswithpvc",
    "Cycling": "cycling",
    "Running": "running",
    "Single-Arm Band Pull-Apart": "singlearmbandpullapart",
    "Lat and Triceps Stretch": "latandtricepsstretch",
    "Single-Arm Dumbbell Reverse Lunge to Romanian Deadlift": "singlearmdumbbellreverselungetoromaniandeadlift",
    "Incline Dumbbell Chest Press": "inclinechestpress",
    "Jogging": "running",
    "Wall Sit": "wallsit",
    "Cable Shrug": "cableshrug",
    "Cable Lateral Raise": "cablelateralraise",
    "Cable Curl": "cablecurl",
    "Hex Bar Deadlift": "hexbardeadlift",
    "Dumbbell Thrusters": "dumbbellthrusters",
    "Dumbbell Skiers": "dumbbellskiers",
    "Single Arm Dumbbell Snatch": "singlearmdumbbellsnatch",
    "Single Arm Dumbbell Swings": "singlearmdumbbellswings",
    "Hack Squat": "hacksquat",
    "Leg Press": "legpress",
    "Alternating Dumbbell Snatch": "alternatingdumbbellsnatch",
    "Dumbbell Chest Press": "dumbbellchestpress",
    "Close Grip Dumbbell Chest Press": "closegripdumbbellchestpress",
    "Lying Dumbbell Skull Crusher": "lyingdumbbellskullcrusher",
    " Lying Dumbbell Skull Crusher": "lyingdumbbellskullcrusher",
    "Incline Dumbbell Chest Flies": "inclinedumbbellchestflies",
    "Single Arm Dumbbell Tricep Extension": "singlearmdumbbelltricepextension",
    "Single Arm Tricep Kickback": "singlearmtricepkickback",
    "Bicep Dumbbell Curl": "bicepdumbbellcurl",
    "Seated Dumbbell Calf Raise": "seateddumbbellcalfraise",
    "Cable Face Pulls": "cablefacepulls",
    "Cable Reverse Fly": "cablereversefly",
    "Cable Tricep Overhead Extension": "cabletricepoverheadextension",
    "Cable Tricep Kickback": "cabletricepkickback",
    "Bent Over Dumbbell Rows": "bentoverdumbbellrows",
    "Reverse Lunges (Body Weight)": "reverselungesbodyweight",
    "Dumbbell Curls": "dumbbellcurls",
    "Rowing Machine": "rowingmachine",
    "Dumbbell Romanian Deadlift": "dumbbellromaniandeadlift",
    "Bent Over Dumbbell Reverse Fly": "bentoverdumbbellreversefly",
    "Spider Curl": "spidercurl",
    "Alternating Dumbbell Curl": "alternatingdumbbellcurl",
    "Alternating Incline Bicep Curls": "alternatinginclinebicepcurls",
    "Cable Face Away Curls": "cablefacingawaycurl",
    "Chest Supported Incline Shrugs": "chestsupportedinclinedshrug",
    "Dumbbell Floor Press": "dumbbellfloorpress",
    "Dumbbell Floor Pause Press": "dumbbellpausefloorpress",
    "Dumbbell Floor Flies": "dumbellfloorchestfly",
    "Floor Skull Crusher": "floorskullcrusher",
    "Incline Machine Press": "inclinedmachinepress",
    "Dumbbell Lateral Raises": "lateralrise",
    "Barbell Romanian Deadlift": "romaniandeadlift",
    "Neutral Grip Shoulder Press": "seateddumbbellshoulderpressneutralgrip",
    "Standing Dumbbell Overhead Press": "standingdumbbelloverheadpress",
    "Half Kneeling One Arm Pulldown": "halfkneelingsinglearmlatpulldown",
    "Pallof Press": "pallofpress"
}


const exerciseData = {
    "Flat bench": { "Min": 6, "Max": 10, "Weight": 5 },
    "Barbell row": { "Min": 6, "Max": 10, "Weight": 10 },
    "Seated Close Grip Press": { "Min": 8, "Max": 12, "Weight": 5 },
    "Single Arm Row": { "Min": 8, "Max": 12, "Weight": 5 },
    "Incline Reverse Fly": { "Min": 8, "Max": 12, "Weight": 5 },
    "Spider Curls": { "Min": 10, "Max": 15, "Weight": 5 },
    "Lying Dumbbell Skull Crusher": { "Min": 8, "Max": 12, "Weight": 5 },
    " Lying Dumbbell Skull Crusher": { "Min": 8, "Max": 12, "Weight": 5 },
    "Alternating Incline Bicep Curls": { "Min": 8, "Max": 12, "Weight": 5 },
    "Triceps Pushdowns": { "Min": 10, "Max": 15, "Weight": 10 },
    "Wrist Curl Flexion": { "Min": 20, "Max": 30, "Weight": 5 },
    "Supine Dead Bug": { "Min": 10, "Max": 15, "Weight": 5 },
    "Back Squat": { "Min": 8, "Max": 12, "Weight": 10 },
    "Dumbbell Romanian Deadlift": { "Min": 5, "Max": 10, "Weight": 5 },
    "Neutral Grip Shoulder Press": { "Min": 10, "Max": 15, "Weight": 5 },
    "Seated Leg Extension": { "Min": 10, "Max": 15, "Weight": 10 },
    "Lying Hamstrings Curl": { "Min": 10, "Max": 15, "Weight": 10 },
    "Lateral Raise": { "Min": 10, "Max": 15, "Weight": 5 },
    "Calf Raise": { "Min": 10, "Max": 20, "Weight": 10 },
    "Incline Chest Press": { "Min": 8, "Max": 12, "Weight": 5 },
    "Seated Lat Pulldown": { "Min": 10, "Max": 15, "Weight": 10 },
    "Incline Machine Press": { "Min": 6, "Max": 10, "Weight": 10 },
    "Half Kneeling One Arm Pulldown": { "Min": 10, "Max": 15, "Weight": 5 },
    "Incline Dumbbell Chest Flies": { "Min": 10, "Max": 15, "Weight": 5 },
    "Chest Supported Incline Shrugs": { "Min": 10, "Max": 15, "Weight": 5 },
    "Cable Face Away Curls": { "Min": 8, "Max": 12, "Weight": 5 },
    "Close Grip Dumbbell Chest Press": { "Min": 8, "Max": 12, "Weight": 5 },
    "Cable Curl": { "Min": 10, "Max": 15, "Weight": 10 },
    "Cable Tricep Overhead Extension": { "Min": 10, "Max": 15, "Weight": 5 },
    "Wrist Curl Extension": { "Min": 10, "Max": 20, "Weight": 5 },
    "Seated Crunch": { "Min": 10, "Max": 15, "Weight": 10 },
    "Reverse Lunge": { "Min": 8, "Max": 12, "Weight": 5 },
    "Leg Press": { "Min": 10, "Max": 15, "Weight": 10 },
    "Dumbbell Lateral Raises": { "Min": 8, "Max": 12, "Weight": 5 },
    "Dumbbell Glute Bridge": { "Min": 10, "Max": 15, "Weight": 5 },

}

module.exports = { exerciseData, exerciseCode }